import pandas as pd
import os
from IPython.display import display
#files = os.listdir('C:/Users/user/Downloads/data')
files = os.listdir('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data')
display(files)
data = pd.DataFrame(columns = ['userId', 'movieId', 'rating', 'timestamp'])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_1.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_2.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_3.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_4.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_5.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_6.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_7.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_8.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_9.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
temp = pd.read_csv(os.path.join('C:/Users/Крис/Documents/GitHub/Skillfactory_Alexander_Stratonov/module_1/data', 'ratings_10.txt'), names = ['userId', 'movieId', 'rating', 'timestamp'] )
data = pd.concat([data, temp])
display(data)
